name: C/C++ CI

on:
  push:
    branches: [v2]
  pull_request:
    branches: [v2]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout esp32-epaper-weatherdisplay repo
        uses: actions/checkout@v2
      - name: esp-idf build
        uses: sebastianPsm/esp-idf-ci-action@1
